version: "3.9"
services:
  sanic_fibonacci:
    image: sanic-fibonacci
    container_name: sanic-fibonacci
    build: .
    ports:
      - "8000:8000"
    command: sanic main:app --host 0.0.0.0 --workers 4
